name: Test conditions
on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        id: set_var
        run: |
          echo $("oldSubmodulesState" == "newSubmodulesState")
          echo "foo=false" >> $GITHUB_OUTPUT; [ "oldSubmodulesState" == "newSubmodulesState" ] && echo "foo=true" >> $GITHUB_OUTPUT
        
      - name: Check condition
        if: ${{steps.set_var.outputs.foo}} == "true"
        run: echo "Foo is 1"
    
